#!/usr/bin/env bash
# Hande error page
#!/usr/bin/env bash
# using redirection
apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://google.com permanent;" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/400_error.html
sed -i '/root \/var\/www\/html;/a error_page 404 /404_error.html;\nlocation = /404_error.html {root /usr/share/nginx/html;\ninternal;}\n' /etc/nginx/sites-enabled/default
service nginx restart
