#!/usr/bin/env bash
# Add a custome parameter to Nginx response header
apt-get update -y
apt-get install nginx -y
echo "Hello World!" >> /var/www/html/index.html
sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://google.com permanent;" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page\n" > /usr/share/nginx/html/custom_404_error.html
sed -i '/root \/var\/www\/html;/a error_page 404 /custom_404_error.html;\nlocation = /custom_404_error.html {\nroot /usr/share/nginx/html; \ninternal;\n}\n' /etc/nginx/sites-enabled/default
sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

service nginx start
