#!/usr/bin/env bash
# print text to infinity with sleep between each times and handle TERM signal
while true; do
    trap "echo 'I am invincible!!!'" SIGTERM
    echo "To infinity and beyond"
    sleep 2
done
