#!/usr/bin/env bash
# print Best School 10 times using while loops

COUNT="1"

while [ $COUNT -le 10 ]; do
      if [ $COUNT -eq 4 ]
      then
          echo "bad luck"
      elif [ $COUNT -eq 8 ]
      then
      	   echo "good luck"
      else
	echo "Best School"
	
	fi
    COUNT=$((COUNT+1))
done
