#!/usr/bin/env bash
# Display 12 hours and 59 minutes


HR=0
MN=0

while [ "$HR" -le 12 ]; do
    echo "Hour: $HR"
    (( MN=1 ))
    while [ "$MN" -le 59 ]; do
	  echo "$MN"
	  (( MN++ ))
    done
    (( HR++ ))
done
