#!/usr/bin/env bash
# Display file info

File_name=school

if [ -e "$File_name" ]
then
    echo "school file exists"
    if [ -s "$File_name" ]
    then
	echo "school file is not empty"
    else
	echo "school file is empty"
    fi
    if [ -f "$File_name" ]
    then
	echo "school is a regular file"
    fi
else
    echo "school file does not exist"
    fi
