#!/usr/bin/env bash
# Run Nginx service as nginx user and other configurations
sed -i 's/user\s.*/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-availabe/default
sudo service nginx restart
